# Server Configuration
server.port=10000

# Application
spring.application.name=anonymous-chat-room

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging
logging.level.com.chat=DEBUG
logging.level.org.springframework.web.socket=DEBUG
